[package]
name = "slint-contract"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
slint-interpreter = { version = "1.18.0", default-features = false, features = ["compat-1-2"] }
spin_on = "0.1.1"
