[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=Xvfb :1 -screen 0 1280x800x24
autorestart=true
stdout_logfile=/tmp/xvfb.log
stderr_logfile=/tmp/xvfb.err

[program:openbox]
command=openbox
autorestart=true
depend_on=xvfb
stdout_logfile=/tmp/openbox.log
stderr_logfile=/tmp/openbox.err

[program:x11vnc]
command=x11vnc -display :1 -N -forever -shared -nopw -rfbport 5900
autorestart=true
depend_on=xvfb
stdout_logfile=/tmp/x11vnc.log
stderr_logfile=/tmp/x11vnc.err

[program:novnc]
command=websockify --web=/usr/share/novnc 6080 127.0.0.1:5900
autorestart=true
depend_on=x11vnc
stdout_logfile=/tmp/novnc.log
stderr_logfile=/tmp/novnc.err
