#!/usr/bin/env bash
set -euxo pipefail

cargo fmt --all -- --check
cargo check --workspace --all-targets
cargo clippy --all-targets --all-features -- -D warnings
cargo check -p desktop --no-default-features
./scripts/slint-check
